services:
  app:
    container_name: load_tester_app
    restart: no
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
    ports:
      - "5173:5173"
  nginx:
    container_name: load_tester_nginx
    image: nginx:1.27.2
    restart: no
    ports:
      - 80:80
    volumes:
      - ./public:/var/www/public
      # - ./storage/app:/var/www/storage/app
      - ./docker-configs/nginx/default.conf:/etc/nginx/conf.d/default.conf
  db:
    image: mariadb:11.2
    container_name: laravel_tester_db
    restart: no
    ports:
      - 3306:3306
    volumes:
      - ./docker-configs/mariadb:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_ROOT_USER: admin
      MARIADB_PASSWORD: password
      MARIADB_USER: admin
      MARIADB_DATABASE: load_tester